#!/bin/bash
# 用于 docxit 命令自动补全的 bash 脚本文件

_docxit_auto_complete()
{
	local docxit_opts="add branch checkout commit config diff help init log merge reset status tag version"
	local docxit_other_opts="--help --version"

	local cur prev files 
	cur="${COMP_WORDS[COMP_CWORD]}"
	prev="${COMP_WORDS[COMP_CWORD-1]}"
	files=$(ls --almost-all --indicator-style=slash)

	if [[ ${prev} == "docxit" ]]
	then
		if [[ ${cur} == --* ]]
		then
			COMPREPLY=( $(compgen -W "${docxit_other_opts}" -- ${cur}) )
		else
			COMPREPLY=( $(compgen -W "${docxit_opts}" -- ${cur}) )
		fi
	else
		COMPREPLY=( $(compgen -W "$files" -- ${cur}) )
	fi
}

complete -F _docxit_auto_complete docxit		# 函数名 要补全的命令名
